I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 59, in script
    if chapter > 0:
  File "game/script.rpy", line 59, in <module>
    if chapter > 0:
NameError: name 'chapter' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 59, in script
    if chapter > 0:
  File "C:\Users\Marisa\Documents\GitHub\Hist12AFinal\renpy-6.99.8-sdk\renpy\ast.py", line 1647, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Marisa\Documents\GitHub\Hist12AFinal\renpy-6.99.8-sdk\renpy\python.py", line 1490, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Marisa\Documents\GitHub\Hist12AFinal\renpy-6.99.8-sdk\renpy\python.py", line 1485, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 59, in <module>
    if chapter > 0:
NameError: name 'chapter' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.8.959
Example 0.0
